### ISSUE TITLE
Interrupt output

### ISSUE THREAD

**Issue by lheinke** [adamyodinsky/TerminalGPT#151]
There might already be a way to do this that I am not aware of, but I could not find anything in the README or `--help` output.

Answers can sometimes take quite a while to get printed to the terminal. If you made a mistake or can already see that the LLM misunderstood your request, it can be quite frustrating to have to wait until it has finished its answer. Therefore, my feature request:

Please add a way to interrupt the output without closing the current session (as CTLR+c would do).

**Comment by adamyodinsky** [comment]
You can just ctrl + c in MacBook and i think also in linux. Not sure what is the equivalent in windows.

**Comment by lheinke** [comment]
Not sure if this was a recent change, but after updating the package, this works as suggested. Thanks for the help.
