### ISSUE TITLE
No matching distribution found for terminalgpt

### ISSUE THREAD

**Issue by khanfar** [adamyodinsky/TerminalGPT#34]
i try setub on ubuntu . when i run pip install terminalgpt -U --user  i got this error : 
Could not find a version that satisfies the requirement terminalgpt (from versions: none)
ERROR: No matching distribution found for terminalgpt

please help

**Comment by Charlz91108112** [comment]
Hello @khanfar ,

Consider the following points:

- I was able to install it in one go.
- Now, on the basis of the error message, I assume that you have more than one versions of python installed. (Please check)
- If yes, then run the following command: `pip3 install terminalgpt -U --user`.
- That is it. I understand that this will help. Please let me know if this works!

And big thanks to the creator @adamyodinsky . I would definitely like to contribute to this project.

**Comment by adamyodinsky** [comment]
Closing
